config/routes.rb
Rails.application.routes.draw do
  namespace :yugioh do
    resources :releases
  end
  namespace :yugioh do
    resources :cards
  end
  namespace :yugioh do
    resources :sets
  end

end

app/models/yugioh.rb
module Yugioh
  def self.table_name_prefix
    'yugioh_'
  end
end

app/models/yugioh/card.rb
class Yugioh::Card < ActiveRecord::Base
  has_many :yugioh_releases, :class_name => 'Yugioh::Release'
  has_many :yugioh_sets, :through => :yugioh_releases, :class_name => 'Yugioh::Set'
end

app/models/yugioh/release.rb
class Yugioh::Release < ActiveRecord::Base
  belongs_to :yugioh_card, :class_name => 'Yugioh::Card'
  belongs_to :yugioh_set, :class_name => 'Yugioh::Set'
end

app/models/yugioh/set.rb
class Yugioh::Set < ActiveRecord::Base
  has_many :yugioh_releases, :class_name => 'Yugioh::Release'
  has_many :yugioh_cards, :through => :yugioh_releases, :class_name => 'Yugioh::Card'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/yugioh/cards_controller.rb
class Yugioh::CardsController < ApplicationController
  before_action :set_yugioh_card, only: [:show, :edit, :update, :destroy]

  # GET /yugioh/cards
  # GET /yugioh/cards.json
  def index
    @yugioh_cards = Yugioh::Card.all
  end

  # GET /yugioh/cards/1
  # GET /yugioh/cards/1.json
  def show
  end

  # GET /yugioh/cards/new
  def new
    @yugioh_card = Yugioh::Card.new
  end

  # GET /yugioh/cards/1/edit
  def edit
  end

  # POST /yugioh/cards
  # POST /yugioh/cards.json
  def create
    @yugioh_card = Yugioh::Card.new(yugioh_card_params)

    respond_to do |format|
      if @yugioh_card.save
        format.html { redirect_to @yugioh_card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @yugioh_card }
      else
        format.html { render :new }
        format.json { render json: @yugioh_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yugioh/cards/1
  # PATCH/PUT /yugioh/cards/1.json
  def update
    respond_to do |format|
      if @yugioh_card.update(yugioh_card_params)
        format.html { redirect_to @yugioh_card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @yugioh_card }
      else
        format.html { render :edit }
        format.json { render json: @yugioh_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yugioh/cards/1
  # DELETE /yugioh/cards/1.json
  def destroy
    @yugioh_card.destroy
    respond_to do |format|
      format.html { redirect_to yugioh_cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yugioh_card
      @yugioh_card = Yugioh::Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yugioh_card_params
      params.require(:yugioh_card).permit(:name, :text, :card_type, :type, :element, :attack, :defense, :level, :property)
    end
end

app/controllers/yugioh/releases_controller.rb
class Yugioh::ReleasesController < ApplicationController
  before_action :set_yugioh_release, only: [:show, :edit, :update, :destroy]

  # GET /yugioh/releases
  # GET /yugioh/releases.json
  def index
    @yugioh_releases = Yugioh::Release.all
  end

  # GET /yugioh/releases/1
  # GET /yugioh/releases/1.json
  def show
  end

  # GET /yugioh/releases/new
  def new
    @yugioh_release = Yugioh::Release.new
  end

  # GET /yugioh/releases/1/edit
  def edit
  end

  # POST /yugioh/releases
  # POST /yugioh/releases.json
  def create
    @yugioh_release = Yugioh::Release.new(yugioh_release_params)

    respond_to do |format|
      if @yugioh_release.save
        format.html { redirect_to @yugioh_release, notice: 'Release was successfully created.' }
        format.json { render :show, status: :created, location: @yugioh_release }
      else
        format.html { render :new }
        format.json { render json: @yugioh_release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yugioh/releases/1
  # PATCH/PUT /yugioh/releases/1.json
  def update
    respond_to do |format|
      if @yugioh_release.update(yugioh_release_params)
        format.html { redirect_to @yugioh_release, notice: 'Release was successfully updated.' }
        format.json { render :show, status: :ok, location: @yugioh_release }
      else
        format.html { render :edit }
        format.json { render json: @yugioh_release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yugioh/releases/1
  # DELETE /yugioh/releases/1.json
  def destroy
    @yugioh_release.destroy
    respond_to do |format|
      format.html { redirect_to yugioh_releases_url, notice: 'Release was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yugioh_release
      @yugioh_release = Yugioh::Release.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yugioh_release_params
      params.require(:yugioh_release).permit(:print_tag, :rarity)
    end
end

app/controllers/yugioh/sets_controller.rb
class Yugioh::SetsController < ApplicationController
  before_action :set_yugioh_set, only: [:show, :edit, :update, :destroy]

  # GET /yugioh/sets
  # GET /yugioh/sets.json
  def index
    @yugioh_sets = Yugioh::Set.all
  end

  # GET /yugioh/sets/1
  # GET /yugioh/sets/1.json
  def show
  end

  # GET /yugioh/sets/new
  def new
    @yugioh_set = Yugioh::Set.new
  end

  # GET /yugioh/sets/1/edit
  def edit
  end

  # POST /yugioh/sets
  # POST /yugioh/sets.json
  def create
    @yugioh_set = Yugioh::Set.new(yugioh_set_params)

    respond_to do |format|
      if @yugioh_set.save
        format.html { redirect_to @yugioh_set, notice: 'Set was successfully created.' }
        format.json { render :show, status: :created, location: @yugioh_set }
      else
        format.html { render :new }
        format.json { render json: @yugioh_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yugioh/sets/1
  # PATCH/PUT /yugioh/sets/1.json
  def update
    respond_to do |format|
      if @yugioh_set.update(yugioh_set_params)
        format.html { redirect_to @yugioh_set, notice: 'Set was successfully updated.' }
        format.json { render :show, status: :ok, location: @yugioh_set }
      else
        format.html { render :edit }
        format.json { render json: @yugioh_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yugioh/sets/1
  # DELETE /yugioh/sets/1.json
  def destroy
    @yugioh_set.destroy
    respond_to do |format|
      format.html { redirect_to yugioh_sets_url, notice: 'Set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yugioh_set
      @yugioh_set = Yugioh::Set.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yugioh_set_params
      params.require(:yugioh_set).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/yugioh/cards_helper.rb
module Yugioh::CardsHelper
end

app/helpers/yugioh/releases_helper.rb
module Yugioh::ReleasesHelper
end

app/helpers/yugioh/sets_helper.rb
module Yugioh::SetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TCGPicker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/yugioh/cards/_form.html.erb
<%= form_for(@yugioh_card) do |f| %>
  <% if @yugioh_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yugioh_card.errors.count, "error") %> prohibited this yugioh_card from being saved:</h2>

      <ul>
      <% @yugioh_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :card_type %><br>
    <%= f.text_field :card_type %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :element %><br>
    <%= f.text_field :element %>
  </div>
  <div class="field">
    <%= f.label :attack %><br>
    <%= f.number_field :attack %>
  </div>
  <div class="field">
    <%= f.label :defense %><br>
    <%= f.number_field :defense %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :property %><br>
    <%= f.text_field :property %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yugioh/cards/edit.html.erb
<h1>Editing Yugioh Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @yugioh_card %> |
<%= link_to 'Back', yugioh_cards_path %>

app/views/yugioh/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Yugioh Cards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Text</th>
      <th>Card type</th>
      <th>Type</th>
      <th>Element</th>
      <th>Attack</th>
      <th>Defense</th>
      <th>Level</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yugioh_cards.each do |yugioh_card| %>
      <tr>
        <td><%= yugioh_card.name %></td>
        <td><%= yugioh_card.text %></td>
        <td><%= yugioh_card.card_type %></td>
        <td><%= yugioh_card.type %></td>
        <td><%= yugioh_card.element %></td>
        <td><%= yugioh_card.attack %></td>
        <td><%= yugioh_card.defense %></td>
        <td><%= yugioh_card.level %></td>
        <td><%= yugioh_card.property %></td>
        <td><%= link_to 'Show', yugioh_card %></td>
        <td><%= link_to 'Edit', edit_yugioh_card_path(yugioh_card) %></td>
        <td><%= link_to 'Destroy', yugioh_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_yugioh_card_path %>

app/views/yugioh/cards/new.html.erb
<h1>New Yugioh Card</h1>

<%= render 'form' %>

<%= link_to 'Back', yugioh_cards_path %>

app/views/yugioh/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @yugioh_card.name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @yugioh_card.text %>
</p>

<p>
  <strong>Card type:</strong>
  <%= @yugioh_card.card_type %>
</p>

<p>
  <strong>Type:</strong>
  <%= @yugioh_card.monster_group %>
</p>

<p>
  <strong>Element:</strong>
  <%= @yugioh_card.element %>
</p>

<p>
  <strong>Attack:</strong>
  <%= @yugioh_card.attack %>
</p>

<p>
  <strong>Defense:</strong>
  <%= @yugioh_card.defense %>
</p>

<p>
  <strong>Level:</strong>
  <%= @yugioh_card.level %>
</p>

<p>
  <strong>Property:</strong>
  <%= @yugioh_card.property %>
</p>

<%= link_to 'Edit', edit_yugioh_card_path(@yugioh_card) %> |
<%= link_to 'Back', yugioh_cards_path %>

app/views/yugioh/releases/_form.html.erb
<%= form_for(@yugioh_release) do |f| %>
  <% if @yugioh_release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yugioh_release.errors.count, "error") %> prohibited this yugioh_release from being saved:</h2>

      <ul>
      <% @yugioh_release.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :print_tag %><br>
    <%= f.text_field :print_tag %>
  </div>
  <div class="field">
    <%= f.label :rarity %><br>
    <%= f.text_field :rarity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yugioh/releases/edit.html.erb
<h1>Editing Yugioh Release</h1>

<%= render 'form' %>

<%= link_to 'Show', @yugioh_release %> |
<%= link_to 'Back', yugioh_releases_path %>

app/views/yugioh/releases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Yugioh Releases</h1>

<table>
  <thead>
    <tr>
      <th>Print tag</th>
      <th>Rarity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yugioh_releases.each do |yugioh_release| %>
      <tr>
        <td><%= yugioh_release.print_tag %></td>
        <td><%= yugioh_release.rarity %></td>
        <td><%= link_to 'Show', yugioh_release %></td>
        <td><%= link_to 'Edit', edit_yugioh_release_path(yugioh_release) %></td>
        <td><%= link_to 'Destroy', yugioh_release, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Release', new_yugioh_release_path %>

app/views/yugioh/releases/new.html.erb
<h1>New Yugioh Release</h1>

<%= render 'form' %>

<%= link_to 'Back', yugioh_releases_path %>

app/views/yugioh/releases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Print tag:</strong>
  <%= @yugioh_release.print_tag %>
</p>

<p>
  <strong>Rarity:</strong>
  <%= @yugioh_release.rarity %>
</p>

<%= link_to 'Edit', edit_yugioh_release_path(@yugioh_release) %> |
<%= link_to 'Back', yugioh_releases_path %>

app/views/yugioh/sets/_form.html.erb
<%= form_for(@yugioh_set) do |f| %>
  <% if @yugioh_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yugioh_set.errors.count, "error") %> prohibited this yugioh_set from being saved:</h2>

      <ul>
      <% @yugioh_set.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yugioh/sets/edit.html.erb
<h1>Editing Yugioh Set</h1>

<%= render 'form' %>

<%= link_to 'Show', @yugioh_set %> |
<%= link_to 'Back', yugioh_sets_path %>

app/views/yugioh/sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Yugioh Sets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yugioh_sets.each do |yugioh_set| %>
      <tr>
        <td><%= yugioh_set.name %></td>
        <td><%= link_to 'Show', yugioh_set %></td>
        <td><%= link_to 'Edit', edit_yugioh_set_path(yugioh_set) %></td>
        <td><%= link_to 'Destroy', yugioh_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Set', new_yugioh_set_path %>

app/views/yugioh/sets/new.html.erb
<h1>New Yugioh Set</h1>

<%= render 'form' %>

<%= link_to 'Back', yugioh_sets_path %>

app/views/yugioh/sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @yugioh_set.name %>

  <table>
    <thead>
      <tr>
        <th>Number</th>
        <th>Card Name</th>
        <th>Type</th>
        <th>Rarity</th>
      </tr>
    </thead>
    <tbody>
      <% ::Yugioh::Release.where(:yugioh_set_id => @yugioh_set.id).order(:print_tag).each do |release| %>
        <tr>
          <td><%= release.print_tag %></td>
          <td><%= link_to release.yugioh_card.name, controller: 'yugioh/cards', action: 'show', id: release.yugioh_card.id %></td>
          <td><%= release.yugioh_card.card_type %></td>
          <td><%= release.rarity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>

<%= link_to 'Edit', edit_yugioh_set_path(@yugioh_set) %> |
<%= link_to 'Back', yugioh_sets_path %>